// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StatusFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusFkeyId");

                    b.HasIndex("UserFkeyId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("api.Models.CardOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardFkeyId")
                        .HasColumnType("integer");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SprintFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardFkeyId");

                    b.HasIndex("SprintFkeyId");

                    b.ToTable("CardOrders");
                });

            modelBuilder.Entity("api.Models.DegreeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DegreeCodes");
                });

            modelBuilder.Entity("api.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("api.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DegreeCodeFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DegreeCodeFkeyId");

                    b.HasIndex("IdFkeyId");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumParticipants")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("api.Models.ProjectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProfessorFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorFkeyId");

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("api.Models.ProjectGroupProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupFkeyId");

                    b.HasIndex("ProjectFkeyId");

                    b.ToTable("ProjectGroupProjects");
                });

            modelBuilder.Entity("api.Models.ProjectRoleCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProjectRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectRoleCodes");
                });

            modelBuilder.Entity("api.Models.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProjectFkeyId")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectFkeyId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("api.Models.RoleCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoleCodes");
                });

            modelBuilder.Entity("api.Models.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpect")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectFkeyId");

                    b.HasIndex("UserFkeyId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("api.Models.SprintCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("SprintFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardFkeyId");

                    b.HasIndex("SprintFkeyId");

                    b.ToTable("SprintCards");
                });

            modelBuilder.Entity("api.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SprintFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SprintFkeyId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("api.Models.StatusOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("SprintFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SprintFkeyId");

                    b.HasIndex("StatusFkeyId");

                    b.ToTable("StatusOrders");
                });

            modelBuilder.Entity("api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GitHub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GroupFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupFkeyId");

                    b.HasIndex("IdFkeyId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoleCodeFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleCodeFkeyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Models.UserProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProjectFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectRoleCodeFkeyId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserFkeyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectFkeyId");

                    b.HasIndex("ProjectRoleCodeFkeyId");

                    b.HasIndex("UserFkeyId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("api.Models.Card", b =>
                {
                    b.HasOne("api.Models.Status", "StatusFkey")
                        .WithMany("Cards")
                        .HasForeignKey("StatusFkeyId");

                    b.HasOne("api.Models.User", "UserFkey")
                        .WithMany("Cards")
                        .HasForeignKey("UserFkeyId");

                    b.Navigation("StatusFkey");

                    b.Navigation("UserFkey");
                });

            modelBuilder.Entity("api.Models.CardOrder", b =>
                {
                    b.HasOne("api.Models.Card", "CardFkey")
                        .WithMany("CardOrders")
                        .HasForeignKey("CardFkeyId");

                    b.HasOne("api.Models.Sprint", "SprintFkey")
                        .WithMany("CardOrders")
                        .HasForeignKey("SprintFkeyId");

                    b.Navigation("CardFkey");

                    b.Navigation("SprintFkey");
                });

            modelBuilder.Entity("api.Models.Professor", b =>
                {
                    b.HasOne("api.Models.DegreeCode", "DegreeCodeFkey")
                        .WithMany("Professors")
                        .HasForeignKey("DegreeCodeFkeyId");

                    b.HasOne("api.Models.User", "IdFkey")
                        .WithMany("Professors")
                        .HasForeignKey("IdFkeyId");

                    b.Navigation("DegreeCodeFkey");

                    b.Navigation("IdFkey");
                });

            modelBuilder.Entity("api.Models.ProjectGroup", b =>
                {
                    b.HasOne("api.Models.Professor", "ProfessorFkey")
                        .WithMany("ProjectGroups")
                        .HasForeignKey("ProfessorFkeyId");

                    b.Navigation("ProfessorFkey");
                });

            modelBuilder.Entity("api.Models.ProjectGroupProject", b =>
                {
                    b.HasOne("api.Models.ProjectGroup", "GroupFkey")
                        .WithMany("ProjectGroupProjects")
                        .HasForeignKey("GroupFkeyId");

                    b.HasOne("api.Models.Project", "ProjectFkey")
                        .WithMany("ProjectGroupProjects")
                        .HasForeignKey("ProjectFkeyId");

                    b.Navigation("GroupFkey");

                    b.Navigation("ProjectFkey");
                });

            modelBuilder.Entity("api.Models.Repository", b =>
                {
                    b.HasOne("api.Models.Project", "ProjectFkey")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjectFkeyId");

                    b.Navigation("ProjectFkey");
                });

            modelBuilder.Entity("api.Models.Sprint", b =>
                {
                    b.HasOne("api.Models.Project", "ProjectFkey")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjectFkeyId");

                    b.HasOne("api.Models.User", "UserFkey")
                        .WithMany("Sprints")
                        .HasForeignKey("UserFkeyId");

                    b.Navigation("ProjectFkey");

                    b.Navigation("UserFkey");
                });

            modelBuilder.Entity("api.Models.SprintCard", b =>
                {
                    b.HasOne("api.Models.Card", "CardFkey")
                        .WithMany("SprintCards")
                        .HasForeignKey("CardFkeyId");

                    b.HasOne("api.Models.Sprint", "SprintFkey")
                        .WithMany("SprintCards")
                        .HasForeignKey("SprintFkeyId");

                    b.Navigation("CardFkey");

                    b.Navigation("SprintFkey");
                });

            modelBuilder.Entity("api.Models.Status", b =>
                {
                    b.HasOne("api.Models.Sprint", "SprintFkey")
                        .WithMany("Statuses")
                        .HasForeignKey("SprintFkeyId");

                    b.Navigation("SprintFkey");
                });

            modelBuilder.Entity("api.Models.StatusOrder", b =>
                {
                    b.HasOne("api.Models.Sprint", "SprintFkey")
                        .WithMany("StatusOrders")
                        .HasForeignKey("SprintFkeyId");

                    b.HasOne("api.Models.Status", "StatusFkey")
                        .WithMany("StatusOrders")
                        .HasForeignKey("StatusFkeyId");

                    b.Navigation("SprintFkey");

                    b.Navigation("StatusFkey");
                });

            modelBuilder.Entity("api.Models.Student", b =>
                {
                    b.HasOne("api.Models.Group", "GroupFkey")
                        .WithMany("Students")
                        .HasForeignKey("GroupFkeyId");

                    b.HasOne("api.Models.User", "IdFkey")
                        .WithMany("Students")
                        .HasForeignKey("IdFkeyId");

                    b.Navigation("GroupFkey");

                    b.Navigation("IdFkey");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.HasOne("api.Models.RoleCode", "RoleCodeFkey")
                        .WithMany("Users")
                        .HasForeignKey("RoleCodeFkeyId");

                    b.Navigation("RoleCodeFkey");
                });

            modelBuilder.Entity("api.Models.UserProject", b =>
                {
                    b.HasOne("api.Models.Project", "ProjectFkey")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectFkeyId");

                    b.HasOne("api.Models.ProjectRoleCode", "ProjectRoleCodeFkey")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectRoleCodeFkeyId");

                    b.HasOne("api.Models.User", "UserFkey")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserFkeyId");

                    b.Navigation("ProjectFkey");

                    b.Navigation("ProjectRoleCodeFkey");

                    b.Navigation("UserFkey");
                });

            modelBuilder.Entity("api.Models.Card", b =>
                {
                    b.Navigation("CardOrders");

                    b.Navigation("SprintCards");
                });

            modelBuilder.Entity("api.Models.DegreeCode", b =>
                {
                    b.Navigation("Professors");
                });

            modelBuilder.Entity("api.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("api.Models.Professor", b =>
                {
                    b.Navigation("ProjectGroups");
                });

            modelBuilder.Entity("api.Models.Project", b =>
                {
                    b.Navigation("ProjectGroupProjects");

                    b.Navigation("Repositories");

                    b.Navigation("Sprints");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("api.Models.ProjectGroup", b =>
                {
                    b.Navigation("ProjectGroupProjects");
                });

            modelBuilder.Entity("api.Models.ProjectRoleCode", b =>
                {
                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("api.Models.RoleCode", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("api.Models.Sprint", b =>
                {
                    b.Navigation("CardOrders");

                    b.Navigation("SprintCards");

                    b.Navigation("StatusOrders");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("api.Models.Status", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("StatusOrders");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Professors");

                    b.Navigation("Sprints");

                    b.Navigation("Students");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
